require:
  - rubocop-performance
  - rubocop-rails

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - .git/**/*
    - public/**/*
    - log/**/*
    - tmp/**/*
    - bin/**/*
    - db/migrate/**/*
    - db/schema.rb

Bundler:
  Enabled: true

Gemspec:
  Enabled: true

Lint:
  Enabled: true

Performance:
  Enabled: true

Security:
  Enabled: true

Style/Documentation:
  Enabled: false

Rails/NotNullColumn:
  Enabled: false

Metrics/MethodLength:
  Max: 15

Metrics/BlockLength:
  Exclude:
    - spec/**/*
    - config/environments/*

Style/ClassAndModuleChildren:
  EnforcedStyle: compact
  Exclude:
    - config/application.rb

Style/FrozenStringLiteralComment:
  Exclude:
    - db/migrate/*
