version: '3'

services:
  web:
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -b '0.0.0.0'"
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "13000:3000"
    tty: true
    stdin_open: true
    volumes:
      - bundle:/usr/local/bundle
      - ./:/app

volumes:
  bundle:
